# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 907f7d7dcc5bfece8c97b74c2d17c0ee671d929bdeb089aef8ec95339e8a19d7b57a442117b0c46b38c76ba816aab9b17fafbf8c15837762a9efde585fc3ec0a

test:
  secret_key_base: 1ae436e8bb8e2e2bcce6588c82b0d380728b3039209c30ef643f1a6dfeb5db56ce1732da1a5825440e3959f6633eeaefc5822305899ea721aac5b6c2a704f055

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
